package com.grizwold.aoc;

import org.junit.Test;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;

public class Day6Test {
    private final Day6 day6 = new Day6();

    @Test
    public void examples() {
        String input = "COM)B\n" +
                "B)C\n" +
                "C)D\n" +
                "D)E\n" +
                "E)F\n" +
                "B)G\n" +
                "G)H\n" +
                "D)I\n" +
                "E)J\n" +
                "J)K\n" +
                "K)L";
        assertThat(day6.orbitsTotal(input), is(42));
    }

    @Test
    public void solution1() {
        String input = "797)67Y\n" +
                "W32)48L\n" +
                "J31)N9K\n" +
                "QQ3)NVL\n" +
                "MP6)JBY\n" +
                "8T3)H27\n" +
                "DRK)THF\n" +
                "BSN)7MD\n" +
                "Z2G)VRX\n" +
                "CVV)XDC\n" +
                "WVW)SV6\n" +
                "D3H)QMG\n" +
                "9BM)NTH\n" +
                "4T7)FQS\n" +
                "F58)D1Q\n" +
                "CR7)B7L\n" +
                "4W8)T9Z\n" +
                "5SB)5JB\n" +
                "DRJ)YQD\n" +
                "76X)X1Z\n" +
                "WC9)LNG\n" +
                "52C)W7J\n" +
                "9ZS)KM7\n" +
                "3RW)C8R\n" +
                "7RQ)TJW\n" +
                "HVN)ZNQ\n" +
                "SQK)CBT\n" +
                "GWC)N76\n" +
                "KBQ)W44\n" +
                "QD5)RVQ\n" +
                "SQF)N3K\n" +
                "RZ1)B2R\n" +
                "TB5)34W\n" +
                "J56)CQD\n" +
                "34Y)HLX\n" +
                "DTM)TD4\n" +
                "2RF)SQV\n" +
                "GJT)TFD\n" +
                "CNK)88B\n" +
                "PJD)GD8\n" +
                "4V8)FQN\n" +
                "HKH)6RS\n" +
                "7T4)2JT\n" +
                "DBM)DMQ\n" +
                "59X)137\n" +
                "HK7)B62\n" +
                "D34)K7Z\n" +
                "RR2)M74\n" +
                "Q13)FC5\n" +
                "1F1)8XJ\n" +
                "K1L)QZ9\n" +
                "T73)4VT\n" +
                "Z7S)59X\n" +
                "1MQ)GB6\n" +
                "BJT)4BZ\n" +
                "WW8)DT2\n" +
                "JYL)6SH\n" +
                "R2K)WC9\n" +
                "21H)4ZD\n" +
                "Z7Z)QWZ\n" +
                "F8N)LRZ\n" +
                "QZ9)9TD\n" +
                "3DP)VDT\n" +
                "GZK)ZGF\n" +
                "G3P)KLZ\n" +
                "7ZM)G3P\n" +
                "3VX)P4H\n" +
                "7T4)LNV\n" +
                "VVV)Q99\n" +
                "BYX)87K\n" +
                "4C1)9XS\n" +
                "SB3)4SV\n" +
                "FYV)JQ4\n" +
                "HQ4)ZMR\n" +
                "K7Z)LKT\n" +
                "TQM)BBH\n" +
                "9V5)PJD\n" +
                "7VB)H6L\n" +
                "66X)FDY\n" +
                "NT9)17R\n" +
                "K9Z)T26\n" +
                "1BX)VRN\n" +
                "TJD)5ST\n" +
                "QWZ)5CT\n" +
                "MD6)GJT\n" +
                "TT1)W3Y\n" +
                "B2R)444\n" +
                "MB8)NFN\n" +
                "FB1)4T3\n" +
                "V3Y)DJ7\n" +
                "2GQ)265\n" +
                "SLV)G3B\n" +
                "THF)DC1\n" +
                "HRR)LV1\n" +
                "QZ7)ZR5\n" +
                "VGS)ZCG\n" +
                "CRY)3L3\n" +
                "3N2)CZ4\n" +
                "Y1B)3WF\n" +
                "YK2)W5C\n" +
                "X15)8ZW\n" +
                "92C)3PV\n" +
                "7Z8)Y4B\n" +
                "PWF)NX2\n" +
                "GPR)QVR\n" +
                "TDL)TRM\n" +
                "W4X)8TH\n" +
                "23H)6KK\n" +
                "4X2)TXV\n" +
                "HQ9)52C\n" +
                "LRG)RWM\n" +
                "38N)YVB\n" +
                "W7F)BSM\n" +
                "3VC)FQC\n" +
                "PS7)Z7Z\n" +
                "2YX)QSG\n" +
                "9PB)4KF\n" +
                "VRX)K9Z\n" +
                "TRM)R2K\n" +
                "WYB)NRD\n" +
                "HJ2)5LM\n" +
                "ZRJ)WWL\n" +
                "7TW)WZR\n" +
                "CBX)7S2\n" +
                "V4N)FSN\n" +
                "17B)88D\n" +
                "F91)LWV\n" +
                "L54)9G4\n" +
                "592)YC1\n" +
                "J24)9KW\n" +
                "GNP)Y7T\n" +
                "KDP)22T\n" +
                "ZNQ)QFZ\n" +
                "8NW)MKC\n" +
                "VSJ)NTD\n" +
                "137)VQS\n" +
                "YB3)MP6\n" +
                "38W)DLK\n" +
                "CJJ)683\n" +
                "59N)GHZ\n" +
                "W3Y)P9Y\n" +
                "733)V2Q\n" +
                "WX6)4GM\n" +
                "RRP)HG8\n" +
                "L6L)YZZ\n" +
                "QRW)YZX\n" +
                "1FD)RMT\n" +
                "HSJ)5V9\n" +
                "RVQ)1KY\n" +
                "9K7)72H\n" +
                "V6S)75V\n" +
                "NB1)SDT\n" +
                "J5N)4R6\n" +
                "QD7)1SR\n" +
                "J6W)3FL\n" +
                "2GQ)FQM\n" +
                "J5N)2K9\n" +
                "2B4)R23\n" +
                "4L5)QXX\n" +
                "7J4)42R\n" +
                "6X7)H2X\n" +
                "8D1)LH7\n" +
                "592)J4Y\n" +
                "6CM)4GW\n" +
                "R6V)KSD\n" +
                "FDL)NKS\n" +
                "P4H)8RZ\n" +
                "46M)L1N\n" +
                "M64)M4K\n" +
                "6K3)KZ9\n" +
                "FH8)1SS\n" +
                "DJ7)BMS\n" +
                "MG1)RQ9\n" +
                "ZRH)5G1\n" +
                "TMT)VQG\n" +
                "11V)W7N\n" +
                "ZM5)QHZ\n" +
                "DSL)8GB\n" +
                "YK5)38P\n" +
                "C1Y)YYJ\n" +
                "H61)8N2\n" +
                "T7W)VVJ\n" +
                "THR)M7F\n" +
                "XXH)3H3\n" +
                "TVX)595\n" +
                "B2B)KBF\n" +
                "76Z)DGL\n" +
                "9PR)X23\n" +
                "ST7)G8Q\n" +
                "1FP)FH8\n" +
                "Q5F)7V2\n" +
                "XKP)2VC\n" +
                "47G)1ZG\n" +
                "QXX)8XD\n" +
                "MNG)KNF\n" +
                "RF3)XD8\n" +
                "K4F)PLX\n" +
                "66D)LXG\n" +
                "TQW)5SP\n" +
                "SBR)ZFT\n" +
                "NMH)8W7\n" +
                "N79)YBM\n" +
                "BK8)JY9\n" +
                "NKS)H8K\n" +
                "LQ5)SNS\n" +
                "TVR)N6T\n" +
                "QXP)M92\n" +
                "YMD)HM8\n" +
                "T84)25S\n" +
                "Q6K)M3K\n" +
                "R23)MZM\n" +
                "CTB)B9Z\n" +
                "DT2)718\n" +
                "9ZD)GXG\n" +
                "KKV)N5K\n" +
                "GBK)TKG\n" +
                "TRG)GMW\n" +
                "KFY)PLY\n" +
                "LSP)RG9\n" +
                "Z31)MBP\n" +
                "LXF)LFF\n" +
                "3JC)MS6\n" +
                "CRY)6ZK\n" +
                "67H)Z6Y\n" +
                "B9Z)674\n" +
                "TWJ)DW2\n" +
                "1PR)4WW\n" +
                "X1J)QZR\n" +
                "128)FLG\n" +
                "GTT)75S\n" +
                "67Y)HNK\n" +
                "H2L)ZRX\n" +
                "9V6)RF3\n" +
                "GRX)TDC\n" +
                "WJR)68N\n" +
                "129)QJ4\n" +
                "FY1)PWF\n" +
                "F5D)RQM\n" +
                "S7K)PVL\n" +
                "88B)C23\n" +
                "YV9)136\n" +
                "5C8)X6V\n" +
                "LDQ)1FD\n" +
                "N55)WYB\n" +
                "WZB)ZT8\n" +
                "SYH)QVB\n" +
                "FWZ)SFX\n" +
                "ZVJ)VXP\n" +
                "L5V)J31\n" +
                "8ZW)4HG\n" +
                "49B)J24\n" +
                "6LC)Z98\n" +
                "G83)4V8\n" +
                "BGX)J9B\n" +
                "6XF)MQJ\n" +
                "54P)BTC\n" +
                "83Z)KZP\n" +
                "BZZ)J9P\n" +
                "RL5)QXQ\n" +
                "YMQ)HH4\n" +
                "3XQ)64P\n" +
                "3BG)SBJ\n" +
                "X7P)N8Y\n" +
                "3HN)L4S\n" +
                "T1P)H61\n" +
                "ZJR)ZZR\n" +
                "1SH)JY7\n" +
                "KTB)LYF\n" +
                "ZLF)BXG\n" +
                "G3B)BRS\n" +
                "8JV)46M\n" +
                "KDX)TP4\n" +
                "DPC)T8P\n" +
                "VRQ)G56\n" +
                "2JZ)M64\n" +
                "YY2)1J2\n" +
                "VSJ)G7W\n" +
                "SJ3)L68\n" +
                "19W)SMN\n" +
                "KJX)GNP\n" +
                "7S3)RP1\n" +
                "VCS)MKK\n" +
                "8C6)7TR\n" +
                "NY3)2LY\n" +
                "9N2)GVQ\n" +
                "9Y1)K9W\n" +
                "PLX)V6S\n" +
                "38P)QNP\n" +
                "V2D)J4Q\n" +
                "TGL)NMG\n" +
                "2N2)NXX\n" +
                "ZBW)G5C\n" +
                "88Y)QTV\n" +
                "NPD)B9Y\n" +
                "NFR)HHP\n" +
                "9Z9)Y49\n" +
                "NTH)LG9\n" +
                "RG9)HHS\n" +
                "Y3P)D7W\n" +
                "D38)4JL\n" +
                "MF5)XGZ\n" +
                "4BB)DJJ\n" +
                "1XF)BZ4\n" +
                "F4Q)MHQ\n" +
                "7QN)FPZ\n" +
                "98T)DXP\n" +
                "MLJ)DMR\n" +
                "ZZC)7P2\n" +
                "5G1)7T4\n" +
                "J9B)VR4\n" +
                "W7K)1LP\n" +
                "8Z2)4K2\n" +
                "N1N)DS1\n" +
                "T73)TQW\n" +
                "RQV)HCS\n" +
                "T8P)6XS\n" +
                "CNK)9WG\n" +
                "3RP)43B\n" +
                "S2K)Z2G\n" +
                "Z3H)P8G\n" +
                "BZ4)QVP\n" +
                "W7J)BN5\n" +
                "ZNJ)91T\n" +
                "6V7)CLD\n" +
                "6SH)6L9\n" +
                "XLQ)YBC\n" +
                "BWN)6RL\n" +
                "DRK)NBG\n" +
                "5ST)LR7\n" +
                "BPM)DNV\n" +
                "3H7)WYV\n" +
                "WNF)BS9\n" +
                "FY1)6K9\n" +
                "3T2)3P4\n" +
                "B45)S1Q\n" +
                "BKX)9ZD\n" +
                "Y7T)9PR\n" +
                "BRS)92N\n" +
                "QLQ)75L\n" +
                "XMQ)XTF\n" +
                "N8Y)LSJ\n" +
                "4Q1)2MG\n" +
                "NT9)NRL\n" +
                "7NT)F18\n" +
                "NRD)CFJ\n" +
                "MDW)QXC\n" +
                "QMG)LCN\n" +
                "LSJ)L24\n" +
                "44J)V5Y\n" +
                "186)18R\n" +
                "91T)RM1\n" +
                "P4B)XVT\n" +
                "JN4)128\n" +
                "JXZ)6PZ\n" +
                "Q36)3RP\n" +
                "6K1)T2C\n" +
                "3S8)3VX\n" +
                "42R)QSD\n" +
                "3WF)66X\n" +
                "LB2)XXH\n" +
                "G3Y)SB3\n" +
                "44G)J99\n" +
                "HPK)2X5\n" +
                "7NH)HGJ\n" +
                "2W6)HTC\n" +
                "HM8)FS4\n" +
                "XFD)9FK\n" +
                "643)L1R\n" +
                "3SQ)VB6\n" +
                "8BQ)N5L\n" +
                "2X5)J3R\n" +
                "1ZS)8LF\n" +
                "21Z)SLK\n" +
                "YL7)FQH\n" +
                "RKK)DMZ\n" +
                "TNY)F96\n" +
                "Y2F)FRV\n" +
                "MN7)BZZ\n" +
                "38X)KWN\n" +
                "75F)8WP\n" +
                "ZR5)N7W\n" +
                "F65)2VB\n" +
                "5PT)84N\n" +
                "F9Y)HRR\n" +
                "SVL)RXH\n" +
                "RB6)NFR\n" +
                "QTV)8CV\n" +
                "58Z)BWN\n" +
                "FQN)BK8\n" +
                "WXC)MLY\n" +
                "683)HF6\n" +
                "T5X)6X6\n" +
                "BC5)WZB\n" +
                "J2H)SQF\n" +
                "DBM)LJQ\n" +
                "FQS)SWH\n" +
                "BFC)SLV\n" +
                "45B)7F8\n" +
                "Z12)6DS\n" +
                "DP1)3T2\n" +
                "SLK)BBN\n" +
                "34Q)6V7\n" +
                "X66)DCJ\n" +
                "V1V)X6C\n" +
                "MR9)Z9T\n" +
                "PMF)VP9\n" +
                "VCL)GNN\n" +
                "B7L)KQ2\n" +
                "95C)F58\n" +
                "2RF)YJJ\n" +
                "KNF)5X4\n" +
                "GJT)YZJ\n" +
                "N9K)XTN\n" +
                "T84)HZW\n" +
                "TJN)6QJ\n" +
                "TB5)Z7W\n" +
                "YKV)YMQ\n" +
                "W6T)1CV\n" +
                "1G3)5ZB\n" +
                "LXG)3MK\n" +
                "YJN)TTD\n" +
                "2Z7)KJN\n" +
                "HHS)KKV\n" +
                "KQ2)D3W\n" +
                "M32)3SK\n" +
                "528)49L\n" +
                "CVH)LB6\n" +
                "QSY)C6J\n" +
                "VQS)KFY\n" +
                "VPJ)95Q\n" +
                "2MG)GCK\n" +
                "B2N)9QV\n" +
                "6N5)5FX\n" +
                "F25)QJB\n" +
                "92Z)7QN\n" +
                "7XN)G62\n" +
                "WQ8)61N\n" +
                "X8F)HG1\n" +
                "6Z4)3YQ\n" +
                "MHQ)SAN\n" +
                "XR9)5XJ\n" +
                "891)H43\n" +
                "VTD)1BJ\n" +
                "48L)MV7\n" +
                "W7W)BQT\n" +
                "S9W)42J\n" +
                "7P2)ZV9\n" +
                "TW7)DXK\n" +
                "CBG)2JK\n" +
                "7H8)KRG\n" +
                "GDW)W4X\n" +
                "G8X)2NW\n" +
                "J99)Y5T\n" +
                "VP9)83G\n" +
                "D17)DKJ\n" +
                "1YF)W9J\n" +
                "RSH)T43\n" +
                "4SV)6V6\n" +
                "M7D)QRQ\n" +
                "3WC)CJJ\n" +
                "45R)45B\n" +
                "WFN)21H\n" +
                "4HG)8C6\n" +
                "NFN)BC5\n" +
                "XWF)BWG\n" +
                "NHR)ST7\n" +
                "H83)NXB\n" +
                "3SK)7GB\n" +
                "ZKW)D34\n" +
                "VDT)1SH\n" +
                "33V)N7F\n" +
                "M8Z)4W8\n" +
                "XPD)WXC\n" +
                "FRY)Z2V\n" +
                "JB4)WR2\n" +
                "YPF)8T3\n" +
                "C8R)LRK\n" +
                "V8L)WQ1\n" +
                "28R)Q7Y\n" +
                "C52)Z18\n" +
                "CBY)GLF\n" +
                "PXR)1F1\n" +
                "4XM)CFG\n" +
                "J8G)V11\n" +
                "RVN)9V6\n" +
                "FZQ)B4V\n" +
                "775)3HN\n" +
                "1B2)X42\n" +
                "VD7)6GY\n" +
                "5WS)91M\n" +
                "JJ2)3RW\n" +
                "3RG)8PX\n" +
                "H4W)KHD\n" +
                "B4Z)J56\n" +
                "8XP)ZHJ\n" +
                "FZ4)6DZ\n" +
                "3QM)1XJ\n" +
                "KQD)WDC\n" +
                "BNV)87P\n" +
                "GHZ)B2J\n" +
                "J4Y)PXR\n" +
                "BMM)LVJ\n" +
                "4JK)WZN\n" +
                "TTD)KNL\n" +
                "TW2)9JZ\n" +
                "6KK)DPC\n" +
                "RZV)FK8\n" +
                "3DR)VSR\n" +
                "PDP)76Z\n" +
                "N7H)X7P\n" +
                "J4L)7VB\n" +
                "2HT)DSL\n" +
                "MV7)ZL3\n" +
                "Q7Y)FHP\n" +
                "7BM)2HT\n" +
                "4KF)FX7\n" +
                "B62)DHN\n" +
                "FJ4)775\n" +
                "Z1V)XFQ\n" +
                "N6T)7MV\n" +
                "136)F4M\n" +
                "FBW)FGV\n" +
                "W5G)Q7R\n" +
                "2G5)21B\n" +
                "F76)LLY\n" +
                "VCX)WJB\n" +
                "BN5)B2N\n" +
                "ZVF)9HQ\n" +
                "BMJ)D17\n" +
                "1Q1)Y6J\n" +
                "6TV)MR9\n" +
                "9FQ)1MQ\n" +
                "FC4)VCT\n" +
                "V2C)YDS\n" +
                "8N2)T7W\n" +
                "N5K)RY7\n" +
                "YPH)WGN\n" +
                "RPY)TVY\n" +
                "6BQ)JJF\n" +
                "1SZ)KDP\n" +
                "1WL)DQW\n" +
                "ZXR)BT3\n" +
                "MS6)JN4\n" +
                "4ZD)DBM\n" +
                "3RL)BM4\n" +
                "4DK)SVL\n" +
                "YZ4)XR1\n" +
                "5R1)FMZ\n" +
                "8W7)JS1\n" +
                "KWN)GZK\n" +
                "SR5)L9J\n" +
                "JX6)X5V\n" +
                "YBC)3S8\n" +
                "H48)BTY\n" +
                "FL4)6WC\n" +
                "GB6)285\n" +
                "64P)B4Z\n" +
                "HCS)LK1\n" +
                "Q5F)R6V\n" +
                "JDC)HKH\n" +
                "PWR)916\n" +
                "RDW)TRJ\n" +
                "V11)9L8\n" +
                "HXY)9VS\n" +
                "RP1)CZD\n" +
                "B9Y)891\n" +
                "P1G)FRZ\n" +
                "QTV)B92\n" +
                "VB6)LYJ\n" +
                "3FL)7PW\n" +
                "QLM)L54\n" +
                "LYQ)6LC\n" +
                "Y5Q)MD6\n" +
                "KQ2)KJX\n" +
                "GQG)1K8\n" +
                "SY7)WK9\n" +
                "77W)K1H\n" +
                "65Z)RFV\n" +
                "H54)4P4\n" +
                "95Q)KTB\n" +
                "VMB)DZS\n" +
                "F3C)1N5\n" +
                "T26)7WW\n" +
                "MSL)CWB\n" +
                "QF5)6LN\n" +
                "TWH)MGK\n" +
                "73Z)7KR\n" +
                "VPP)LR8\n" +
                "129)CBX\n" +
                "G8Q)L5V\n" +
                "9V7)RLB\n" +
                "B2X)YPR\n" +
                "T2D)M3M\n" +
                "TT1)4QD\n" +
                "89C)JCX\n" +
                "T7S)7QJ\n" +
                "6WC)SXQ\n" +
                "Z3H)YPM\n" +
                "MBP)7Z8\n" +
                "D3W)G83\n" +
                "QXX)74K\n" +
                "SSB)V2D\n" +
                "QVM)ZBL\n" +
                "WZ1)Z6G\n" +
                "D8J)GQG\n" +
                "9CF)F1C\n" +
                "YDP)TWH\n" +
                "FZ9)T3M\n" +
                "ZTQ)V9X\n" +
                "RX7)7F1\n" +
                "L3H)6NF\n" +
                "BSM)TBV\n" +
                "Z2V)D6G\n" +
                "YS7)W32\n" +
                "LWV)7ZB\n" +
                "PSP)YJR\n" +
                "49C)DWM\n" +
                "88D)3SZ\n" +
                "LX9)G2Z\n" +
                "46D)GKR\n" +
                "Z7W)1PR\n" +
                "PWK)NY3\n" +
                "WDC)Z1V\n" +
                "ZGF)PBN\n" +
                "W28)HX3\n" +
                "5WQ)49B\n" +
                "DYK)B5C\n" +
                "4R6)HK3\n" +
                "HZ2)N7H\n" +
                "MN8)G4Y\n" +
                "SJW)B2X\n" +
                "4M5)6QW\n" +
                "YVC)PDW\n" +
                "D1Q)C97\n" +
                "3SZ)7FW\n" +
                "N6M)MF5\n" +
                "P53)XWC\n" +
                "G46)RDW\n" +
                "F6H)G9N\n" +
                "XTF)BNV\n" +
                "6LC)K8B\n" +
                "2XV)813\n" +
                "7TR)J26\n" +
                "HC4)K38\n" +
                "9QV)VG8\n" +
                "F7Y)58Z\n" +
                "N7W)V4N\n" +
                "YZX)35W\n" +
                "VCJ)1SN\n" +
                "R85)1FP\n" +
                "WHT)681\n" +
                "QCJ)RHP\n" +
                "2T5)ZTX\n" +
                "VXP)XKP\n" +
                "DVZ)2VX\n" +
                "RDF)6FN\n" +
                "DLR)RXK\n" +
                "M66)F8N\n" +
                "BQD)TW1\n" +
                "9L8)2BL\n" +
                "4T5)M36\n" +
                "8FJ)3PK\n" +
                "MLF)7TW\n" +
                "LR8)VZJ\n" +
                "TMH)P2Z\n" +
                "8TH)LFP\n" +
                "FB6)66D\n" +
                "3P2)4T5\n" +
                "BGZ)K4F\n" +
                "75V)F4Q\n" +
                "TP4)8K6\n" +
                "4JL)KGH\n" +
                "N5L)LFC\n" +
                "F5D)WN4\n" +
                "RMT)T5C\n" +
                "1JB)XSJ\n" +
                "MDB)WDX\n" +
                "Y4B)765\n" +
                "1BY)MDW\n" +
                "KYQ)48R\n" +
                "KDD)6K3\n" +
                "YZ2)517\n" +
                "DC1)V5V\n" +
                "JS1)6C9\n" +
                "FVR)3L7\n" +
                "CCQ)HQ9\n" +
                "LB6)JPM\n" +
                "SWH)W28\n" +
                "WVM)K8N\n" +
                "L7T)GPF\n" +
                "4X5)98T\n" +
                "J1V)97M\n" +
                "XHZ)FZQ\n" +
                "J2L)CQ1\n" +
                "Z9T)W7F\n" +
                "3XQ)F25\n" +
                "XYS)M66\n" +
                "PFM)92C\n" +
                "144)F91\n" +
                "7ZB)PFM\n" +
                "GPK)HXY\n" +
                "BBN)MLJ\n" +
                "1KY)3QM\n" +
                "7FW)8BQ\n" +
                "NP8)N2C\n" +
                "CLY)QLQ\n" +
                "HN5)VD7\n" +
                "1CV)H7D\n" +
                "QCJ)TDZ\n" +
                "G9N)HLN\n" +
                "WYK)8H7\n" +
                "NRL)QXS\n" +
                "XMF)WHQ\n" +
                "SQV)2G5\n" +
                "YQM)VZX\n" +
                "NMX)SR5\n" +
                "T4P)6VG\n" +
                "3SQ)S47\n" +
                "1BJ)Q36\n" +
                "QXS)51X\n" +
                "HX3)KGJ\n" +
                "28V)GGC\n" +
                "2VC)6BL\n" +
                "4Q8)RVX\n" +
                "CKW)GTT\n" +
                "JX4)XCB\n" +
                "NDH)Z8W\n" +
                "HJ2)S2K\n" +
                "S6Z)NMX\n" +
                "N76)6TV\n" +
                "RLD)Q8V\n" +
                "R1Q)K7V\n" +
                "FRV)RQK\n" +
                "FJF)RLS\n" +
                "KBF)SWF\n" +
                "VJP)Y2F\n" +
                "LW6)PMF\n" +
                "7MD)67H\n" +
                "456)S3D\n" +
                "DW4)23D\n" +
                "KVT)CVH\n" +
                "NGC)1YF\n" +
                "FX7)JX4\n" +
                "674)HBV\n" +
                "77G)7H8\n" +
                "MZ6)528\n" +
                "NX2)WGD\n" +
                "TZR)CLZ\n" +
                "YY7)4TQ\n" +
                "K8B)GR9\n" +
                "S1Z)WF2\n" +
                "H5F)CKS\n" +
                "W3R)J1V\n" +
                "DTH)28R\n" +
                "9SK)7NH\n" +
                "Q8V)X9B\n" +
                "WJB)4FK\n" +
                "5SP)VJP\n" +
                "3ZL)8Z2\n" +
                "C6J)H85\n" +
                "YR7)4JK\n" +
                "YS7)RVN\n" +
                "BPM)H83\n" +
                "Q1Y)ZWH\n" +
                "4JM)561\n" +
                "MVM)6X7\n" +
                "T6Q)TW2\n" +
                "TPT)47G\n" +
                "QVB)144\n" +
                "VSR)H48\n" +
                "GPS)FJF\n" +
                "RFB)T4B\n" +
                "VP7)3C9\n" +
                "2D8)FZ4\n" +
                "DWM)Y61\n" +
                "YJN)C52\n" +
                "1JB)ZG5\n" +
                "2K9)J7F\n" +
                "3MK)4XM\n" +
                "YB3)PS7\n" +
                "COM)WV2\n" +
                "PDW)T1P\n" +
                "4YP)Q13\n" +
                "BTC)ZBW\n" +
                "9FS)37V\n" +
                "87P)XP2\n" +
                "7F1)RTN\n" +
                "HKR)ZKW\n" +
                "NHL)2XV\n" +
                "PP4)CBG\n" +
                "SDT)9CF\n" +
                "HLN)GBK\n" +
                "Y21)GPS\n" +
                "H42)FJ4\n" +
                "FFZ)DDD\n" +
                "SF7)YZ2\n" +
                "LP4)VSK\n" +
                "FK8)W5G\n" +
                "RFF)2FM\n" +
                "517)FDL\n" +
                "9FK)TW7\n" +
                "83H)S1M\n" +
                "S4T)D8G\n" +
                "9TZ)89C\n" +
                "G7W)VMB\n" +
                "4TQ)V7H\n" +
                "JGP)Z95\n" +
                "V9X)VCS\n" +
                "8P7)DN2\n" +
                "WKZ)95C\n" +
                "L9J)Z8M\n" +
                "M36)FHD\n" +
                "BBH)T3G\n" +
                "XHZ)DP1\n" +
                "VZJ)39J\n" +
                "FVR)YV9\n" +
                "Z95)XK9\n" +
                "D5Y)HTZ\n" +
                "8JH)ZXS\n" +
                "B9D)VHJ\n" +
                "YQD)XPD\n" +
                "9Z8)ZRT\n" +
                "285)X66\n" +
                "F94)D5Y\n" +
                "C23)G3T\n" +
                "7SR)PWR\n" +
                "LK1)K79\n" +
                "X42)8JV\n" +
                "3K2)LSP\n" +
                "DHH)QF5\n" +
                "B92)H2L\n" +
                "7QJ)MPR\n" +
                "FYH)BYX\n" +
                "QCT)PFC\n" +
                "VQG)PQ8\n" +
                "KNL)4SC\n" +
                "QJB)YOU\n" +
                "YKH)YY2\n" +
                "S1M)T92\n" +
                "6PW)11V\n" +
                "HMT)CQY\n" +
                "FHD)MTV\n" +
                "Z6G)PVR\n" +
                "4Q1)6N5\n" +
                "N3M)38W\n" +
                "VCT)CCQ\n" +
                "9KW)BMF\n" +
                "QSG)4C1\n" +
                "J7T)GST\n" +
                "FVN)TY8\n" +
                "X6C)4YN\n" +
                "KRG)Q1Y\n" +
                "CDD)7FS\n" +
                "KDM)K1L\n" +
                "NXB)QR4\n" +
                "XFQ)FZN\n" +
                "1T4)KYQ\n" +
                "QVR)34Q\n" +
                "W6S)TSK\n" +
                "XLD)YKH\n" +
                "75R)TH8\n" +
                "T9Z)5NG\n" +
                "C97)YJF\n" +
                "PSZ)33Z\n" +
                "GNN)R49\n" +
                "36J)N3H\n" +
                "MYL)N1Z\n" +
                "WPP)RHG\n" +
                "2VX)T6Q\n" +
                "XP2)DG9\n" +
                "S21)Z1Q\n" +
                "NMG)YDV\n" +
                "SLV)BGZ\n" +
                "931)KQD\n" +
                "1DB)XGB\n" +
                "SXQ)WCX\n" +
                "K59)XBB\n" +
                "TXV)ZVF\n" +
                "DG9)Y3N\n" +
                "H27)3ZZ\n" +
                "XY8)ZZC\n" +
                "Q7R)V8L\n" +
                "W9J)WFN\n" +
                "8H7)J1X\n" +
                "QJ4)DXJ\n" +
                "GST)Q6K\n" +
                "YDS)JXP\n" +
                "GMW)83M\n" +
                "TFD)P3N\n" +
                "XTN)PKR\n" +
                "9HQ)5H6\n" +
                "BTB)685\n" +
                "3PN)D3H\n" +
                "6NT)F3C\n" +
                "JXP)77W\n" +
                "D8G)XHY\n" +
                "QZ9)L2J\n" +
                "75L)SQK\n" +
                "XWC)8YX\n" +
                "L1N)GS2\n" +
                "JQ8)31Y\n" +
                "TZQ)FVK\n" +
                "DN2)YPH\n" +
                "DW2)8NW\n" +
                "RRQ)2T5\n" +
                "S81)DT5\n" +
                "S3X)V3Y\n" +
                "XBB)FVR\n" +
                "BFV)9DQ\n" +
                "9PR)Z3Z\n" +
                "92N)PLM\n" +
                "B5C)NZR\n" +
                "3C9)LJ5\n" +
                "CQ1)HPK\n" +
                "LR7)BGX\n" +
                "37V)D61\n" +
                "LRK)SP9\n" +
                "JY1)HQ4\n" +
                "RQM)WKZ\n" +
                "8X9)TJQ\n" +
                "DS4)KWB\n" +
                "LG9)JXZ\n" +
                "HG8)MN8\n" +
                "KGJ)BYK\n" +
                "2JK)FMR\n" +
                "WB1)GB9\n" +
                "WGD)TT1\n" +
                "Z3Z)RTL\n" +
                "CDQ)6PW\n" +
                "8V8)2HD\n" +
                "CCC)W7K\n" +
                "YMQ)1WL\n" +
                "GRY)WB1\n" +
                "4QK)DS4\n" +
                "FQH)SSB\n" +
                "Z8W)648\n" +
                "GPD)Q5F\n" +
                "ZBL)LCK\n" +
                "6RL)ZTM\n" +
                "7MV)6Z4\n" +
                "QSY)B9D\n" +
                "N55)SVN\n" +
                "G62)1B2\n" +
                "91R)Q1L\n" +
                "G3P)GX2\n" +
                "PVL)1YW\n" +
                "J9B)JJ2\n" +
                "TNS)PHY\n" +
                "MGK)XZG\n" +
                "RFV)3XQ\n" +
                "1XJ)23H\n" +
                "G3T)Z5H\n" +
                "3RK)T1W\n" +
                "T92)MXC\n" +
                "XDC)HG6\n" +
                "WJQ)PRY\n" +
                "XCB)D8Z\n" +
                "K4R)K32\n" +
                "XYS)46D\n" +
                "RK4)931\n" +
                "7FS)442\n" +
                "RQ9)YV4\n" +
                "KFV)RDF\n" +
                "YC1)2B4\n" +
                "CBT)WHT\n" +
                "JGZ)RTB\n" +
                "C19)HYY\n" +
                "RM1)PDP\n" +
                "SFX)RK4\n" +
                "V5V)JYL\n" +
                "RXK)T57\n" +
                "17R)3DR\n" +
                "CQL)JK6\n" +
                "SP9)WVM\n" +
                "ZG5)T7N\n" +
                "QD7)YL7\n" +
                "ZFT)3RG\n" +
                "PLM)SH8\n" +
                "RP6)VPP\n" +
                "12T)K4R\n" +
                "G9F)KFV\n" +
                "MGG)72P\n" +
                "85L)DPB\n" +
                "GWP)L6L\n" +
                "NHD)WYK\n" +
                "XK8)9ND\n" +
                "T5X)ZXY\n" +
                "6QJ)8X9\n" +
                "4MY)RP6\n" +
                "WN4)W9L\n" +
                "7CW)JH8\n" +
                "1JN)R7V\n" +
                "7KR)Q1G\n" +
                "YHT)5WR\n" +
                "GLP)FHT\n" +
                "59X)TLM\n" +
                "8LS)RKB\n" +
                "4MY)LKV\n" +
                "NQW)VPJ\n" +
                "J7F)R1Q\n" +
                "WWL)77G\n" +
                "LH7)YVC\n" +
                "LR2)SVZ\n" +
                "826)2Z7\n" +
                "C8R)HJ2\n" +
                "8WP)GFJ\n" +
                "X23)FB6\n" +
                "RM1)76X\n" +
                "1Z6)BMJ\n" +
                "1FR)51P\n" +
                "LCK)VFT\n" +
                "ZL3)75R\n" +
                "KWB)L7T\n" +
                "6ZW)826\n" +
                "NZR)3K2\n" +
                "FQC)VHL\n" +
                "YPM)YPJ\n" +
                "2FM)CNL\n" +
                "4TQ)HTP\n" +
                "WGD)36J\n" +
                "PBN)9FQ\n" +
                "YVC)C2P\n" +
                "S49)YJN\n" +
                "QLX)SZC\n" +
                "Z8W)BFC\n" +
                "3ZZ)8D1\n" +
                "WJV)JDP\n" +
                "Z7W)QPK\n" +
                "VZL)9VZ\n" +
                "KLZ)K5Q\n" +
                "SWS)TPT\n" +
                "R68)VFM\n" +
                "SXM)J4L\n" +
                "L71)BTB\n" +
                "8GB)6D5\n" +
                "9WG)P6P\n" +
                "J52)SYH\n" +
                "D6G)T25\n" +
                "TBV)F9Y\n" +
                "R3Y)NHL\n" +
                "5XF)S84\n" +
                "VTZ)Z31\n" +
                "HZW)XMT\n" +
                "DGL)W6S\n" +
                "7TN)QJN\n" +
                "2JT)WJQ\n" +
                "XSJ)9XN\n" +
                "YG4)X15\n" +
                "JY7)DTM\n" +
                "B9Z)MGG\n" +
                "YJJ)Y8G\n" +
                "B4V)R6F\n" +
                "TFF)TDL\n" +
                "TNS)FYH\n" +
                "FDY)CCM\n" +
                "HG6)H2H\n" +
                "N5L)Z2N\n" +
                "FWZ)V1Z\n" +
                "CFG)GYM\n" +
                "23D)BJT\n" +
                "BGD)CLY\n" +
                "GXG)9FS\n" +
                "ZWH)T73\n" +
                "J24)D4X\n" +
                "88N)BGJ\n" +
                "LH7)K5Y\n" +
                "3MC)7S3\n" +
                "TJW)Z7S\n" +
                "ZK7)695\n" +
                "1DM)19W\n" +
                "51P)DVX\n" +
                "N1Z)1SZ\n" +
                "JPM)3N2\n" +
                "6D5)M32\n" +
                "VVJ)KDM\n" +
                "FHP)19S\n" +
                "WCX)VZL\n" +
                "4FK)5XF\n" +
                "DZQ)SWS\n" +
                "QRQ)J52\n" +
                "RHP)ZHT\n" +
                "5RR)92Z\n" +
                "3P4)D5N\n" +
                "1XJ)38N\n" +
                "YFB)C19\n" +
                "1MT)S6T\n" +
                "8K5)QD8\n" +
                "W86)NGC\n" +
                "ZV9)8FJ\n" +
                "GYM)GDP\n" +
                "7LS)HMT\n" +
                "LCN)S7K\n" +
                "K32)7RQ\n" +
                "NFR)S6Z\n" +
                "Q6K)CNK\n" +
                "LYF)RRP\n" +
                "8XJ)R6G\n" +
                "N1Y)DZQ\n" +
                "PQ8)H78\n" +
                "HYY)J2H\n" +
                "8MB)5R1\n" +
                "YDV)4GG\n" +
                "8YX)V62\n" +
                "84V)46L\n" +
                "LNV)KVC\n" +
                "6X6)TMH\n" +
                "BPL)33V\n" +
                "6V6)YMM\n" +
                "JZJ)QWP\n" +
                "4T3)VSJ\n" +
                "DNH)JX6\n" +
                "ZFT)VCX\n" +
                "KSD)YMD\n" +
                "HYR)F64\n" +
                "GLF)7Q6\n" +
                "FPT)84V\n" +
                "R6G)YK5\n" +
                "NNT)H4W\n" +
                "TJD)WKD\n" +
                "RWZ)VMM\n" +
                "NLW)85L\n" +
                "4YN)SQR\n" +
                "8N2)9ZS\n" +
                "N3K)YHT\n" +
                "2S1)SYL\n" +
                "CCM)5MS\n" +
                "GVQ)HC4\n" +
                "VM5)W3Q\n" +
                "WQ1)FWZ\n" +
                "RQK)GZM\n" +
                "HNK)8DX\n" +
                "D6J)GRY\n" +
                "TZQ)RZV\n" +
                "WHQ)SVY\n" +
                "WVM)3DP\n" +
                "Z7Z)PKM\n" +
                "C2K)N1Y\n" +
                "Z2N)9HB\n" +
                "CRZ)4YM\n" +
                "H78)MB8\n" +
                "8RH)8LW\n" +
                "NBG)2BG\n" +
                "XSW)TMT\n" +
                "561)LRG\n" +
                "1N5)4M5\n" +
                "FLW)YBZ\n" +
                "6RP)3QH\n" +
                "M92)R58\n" +
                "CZ7)RDL\n" +
                "FGV)ZPV\n" +
                "RXF)CDQ\n" +
                "9XS)W7W\n" +
                "9VZ)4X2\n" +
                "VRX)WPP\n" +
                "LYJ)VXH\n" +
                "681)YSC\n" +
                "PFC)5CQ\n" +
                "7G7)X8F\n" +
                "T57)FY1\n" +
                "Z8Z)BKX\n" +
                "Z5P)YDP\n" +
                "CQD)T1D\n" +
                "8HF)BSN\n" +
                "YZJ)HVJ\n" +
                "KRL)N55\n" +
                "4KR)4DK\n" +
                "P2D)KVT\n" +
                "RLC)YPF\n" +
                "GX2)4JM\n" +
                "V2Q)7F5\n" +
                "FQM)L2G\n" +
                "SGD)WC5\n" +
                "HTC)SJG\n" +
                "F1C)GDW\n" +
                "WDX)G21\n" +
                "HBV)CVV\n" +
                "7F5)1Z6\n" +
                "LNK)HFD\n" +
                "JB4)DFP\n" +
                "7S2)85B\n" +
                "S1Z)HKR\n" +
                "2LY)LX9\n" +
                "T2C)DGK\n" +
                "HLX)Z6L\n" +
                "4FM)NDH\n" +
                "TRJ)TQM\n" +
                "49L)JY1\n" +
                "MPR)3T6\n" +
                "CWM)9SK\n" +
                "52C)9BX\n" +
                "JBY)DVW\n" +
                "V9C)DLR\n" +
                "ZHT)86L\n" +
                "MBH)NG2\n" +
                "7SR)G4D\n" +
                "35M)MYL\n" +
                "NTD)QCT\n" +
                "2TX)1P3\n" +
                "8RZ)8VK\n" +
                "WYP)N2S\n" +
                "7Z8)2RF\n" +
                "SJG)29X\n" +
                "7WW)GDT\n" +
                "VRN)QZ7\n" +
                "7LG)YK2\n" +
                "765)XLD\n" +
                "P3N)TRG\n" +
                "GCK)RSH\n" +
                "TLM)GPK\n" +
                "M79)4FX\n" +
                "XGB)RL5\n" +
                "RXH)PKH\n" +
                "YHB)LR2\n" +
                "265)1G3\n" +
                "MCG)NHR\n" +
                "3PV)BPM\n" +
                "LM3)TFF\n" +
                "Y49)1BX\n" +
                "GB9)W1Q\n" +
                "GKR)45R\n" +
                "2LF)CHQ\n" +
                "595)X41\n" +
                "W2G)7CW\n" +
                "YB6)83Z\n" +
                "8LF)2W6\n" +
                "GJG)H42\n" +
                "PKR)3Z6\n" +
                "FLL)G7S\n" +
                "WZS)ZFJ\n" +
                "GB4)88N\n" +
                "8BK)CQM\n" +
                "9VS)W2G\n" +
                "5CT)YYD\n" +
                "G4Y)N79\n" +
                "KJN)Y1T\n" +
                "RY7)LBS\n" +
                "K16)FLL\n" +
                "YPF)LW6\n" +
                "SBJ)CRY\n" +
                "4DZ)186\n" +
                "4GG)5WQ\n" +
                "KDV)4DZ\n" +
                "Q1L)H54\n" +
                "R9Z)733\n" +
                "YPJ)GLT\n" +
                "LNP)WVW\n" +
                "XPD)21Z\n" +
                "9V2)HK7\n" +
                "4WW)37W\n" +
                "8K6)FBW\n" +
                "R3Y)LM3\n" +
                "5M2)VM5\n" +
                "ZNJ)DVZ\n" +
                "DVH)1NW\n" +
                "GLT)HM1\n" +
                "SLK)PWK\n" +
                "84N)6K1\n" +
                "GS2)88Y\n" +
                "K1H)GWP\n" +
                "4GW)ZRJ\n" +
                "DVX)PZG\n" +
                "VSF)5GL\n" +
                "WBS)4DV\n" +
                "8XD)S49\n" +
                "V6J)4T7\n" +
                "75S)YKR\n" +
                "GZM)BGD\n" +
                "NKS)LKD\n" +
                "29X)LYQ\n" +
                "JY9)2YX\n" +
                "HBY)73Z\n" +
                "BMF)LP4\n" +
                "T4B)KC2\n" +
                "87K)5M2\n" +
                "QZR)FLW\n" +
                "GR9)KRL\n" +
                "TXB)6NT\n" +
                "4FK)4MY\n" +
                "B31)2LX\n" +
                "TG1)4YP\n" +
                "BQT)LNK\n" +
                "TW1)RB6\n" +
                "3L7)T4P\n" +
                "Z8Z)N3M\n" +
                "6TF)CR7\n" +
                "LFC)R33\n" +
                "37W)1FL\n" +
                "CQY)J5N\n" +
                "S4G)VTD\n" +
                "ZT8)RZ1\n" +
                "5CQ)1FR\n" +
                "BXG)FB1\n" +
                "9G4)BPL\n" +
                "ZCG)F65\n" +
                "ZZR)2NC\n" +
                "WZR)59N\n" +
                "6C9)V2C\n" +
                "ZFJ)P1G\n" +
                "CWB)KYN\n" +
                "SY4)R85\n" +
                "DLK)9V2\n" +
                "2LX)VGN\n" +
                "5JB)GPR\n" +
                "QHZ)9K7\n" +
                "D8Z)2LF\n" +
                "395)NB1\n" +
                "1FL)FBF\n" +
                "5MS)4XD\n" +
                "HF6)49C\n" +
                "JL7)YDQ\n" +
                "33Z)TG1\n" +
                "CXL)X8Y\n" +
                "KYM)8XP\n" +
                "RTB)54P\n" +
                "LZ3)WJR\n" +
                "6DZ)969\n" +
                "FC5)XH7\n" +
                "DKJ)MCG\n" +
                "QCR)VCJ\n" +
                "W32)QXP\n" +
                "2XS)7LG\n" +
                "Z6G)KDX\n" +
                "H43)1SJ\n" +
                "R7V)G7M\n" +
                "YV4)8V8\n" +
                "D4X)1Q1\n" +
                "QSD)3KQ\n" +
                "SFX)M6F\n" +
                "DZ2)4DY\n" +
                "6K9)1DB\n" +
                "CZD)2TX\n" +
                "3Z6)RRQ\n" +
                "72H)3H7\n" +
                "7BM)QRW\n" +
                "P1G)NPF\n" +
                "85B)71W\n" +
                "FRV)MMC\n" +
                "21B)5RR\n" +
                "CSL)VCL\n" +
                "XGZ)CDD\n" +
                "2B4)V9C\n" +
                "QD5)T2M\n" +
                "VMM)456\n" +
                "G56)S1Z\n" +
                "NR6)C1N\n" +
                "NXX)HMR\n" +
                "H2H)XSW\n" +
                "D7W)GPD\n" +
                "JBY)ZNJ\n" +
                "WKD)KDV\n" +
                "7PN)MD2\n" +
                "GDT)G6Q\n" +
                "LV1)7XN\n" +
                "3KQ)RHW\n" +
                "SWF)XLQ\n" +
                "YDS)FL4\n" +
                "45R)Z8Z\n" +
                "K4F)K59\n" +
                "HLJ)QD5\n" +
                "11H)MX8\n" +
                "MKC)VH3\n" +
                "G21)NT9\n" +
                "QXQ)L6Q\n" +
                "VJ2)GFS\n" +
                "HWJ)P4B\n" +
                "B33)3P2\n" +
                "W28)2QR\n" +
                "C1N)8LS\n" +
                "9KW)PSZ\n" +
                "74K)6ZT\n" +
                "B23)WZ6\n" +
                "PPG)GJG\n" +
                "PKM)4QK\n" +
                "BS9)T7S\n" +
                "F96)39P\n" +
                "444)RM5\n" +
                "T6Q)BWD\n" +
                "S7K)M7D\n" +
                "YYD)M79\n" +
                "D1P)116\n" +
                "4DV)J6W\n" +
                "J7F)FRY\n" +
                "SVY)TZQ\n" +
                "8PX)1ZS\n" +
                "QFZ)NKW\n" +
                "FD8)YB6\n" +
                "CLY)X6W\n" +
                "1YW)RFB\n" +
                "648)3MC\n" +
                "7D7)8TJ\n" +
                "DT5)B33\n" +
                "T3M)5C8\n" +
                "31Y)FYV\n" +
                "T43)75F\n" +
                "H46)RFF\n" +
                "3BR)J8G\n" +
                "7S7)WBS\n" +
                "G9F)C39\n" +
                "2QR)12T\n" +
                "MKK)7LS\n" +
                "D1P)RX1\n" +
                "X8Y)CS3\n" +
                "7PN)CRZ\n" +
                "QMG)XNK\n" +
                "YMD)3JC\n" +
                "YSC)S21\n" +
                "DKZ)VWQ\n" +
                "C1Y)G9Y\n" +
                "DS1)Z4P\n" +
                "T2M)9BM\n" +
                "38X)XMF\n" +
                "MZM)DZ2\n" +
                "DXK)YQQ\n" +
                "HGJ)YZ4\n" +
                "VCL)7BM\n" +
                "ZPV)SN4\n" +
                "7J9)6XF\n" +
                "QWP)RKK\n" +
                "TSK)CQL\n" +
                "BMS)TVX\n" +
                "NPF)VJ2\n" +
                "KC2)NP8\n" +
                "MX8)YQM\n" +
                "TH8)RLD\n" +
                "KM7)F76\n" +
                "ZRT)XJR\n" +
                "VWQ)V6J\n" +
                "MKC)SY7\n" +
                "WGN)HLJ\n" +
                "CXL)4Q8\n" +
                "1LP)8RH\n" +
                "MQJ)KD7\n" +
                "7R8)R9Z\n" +
                "3H3)JL7\n" +
                "Y8G)LNP\n" +
                "4VT)P51\n" +
                "2NC)MLF\n" +
                "12H)HVN\n" +
                "HVJ)MN7\n" +
                "SZC)7J4\n" +
                "5X4)D1P\n" +
                "29N)NMH\n" +
                "8LW)L71\n" +
                "YYJ)G46\n" +
                "LDL)CQ3\n" +
                "KHG)6MS\n" +
                "RR2)83H\n" +
                "35D)38X\n" +
                "SV6)XMQ\n" +
                "KHD)MSL\n" +
                "FGB)XFD\n" +
                "ZS2)LXF\n" +
                "DMQ)FZ9\n" +
                "MMC)FGB\n" +
                "JW7)34Y\n" +
                "WGN)VRQ\n" +
                "LRZ)TB5\n" +
                "6NF)4FV\n" +
                "DMR)9N2\n" +
                "916)SY4\n" +
                "83G)WJV\n" +
                "65M)12H\n" +
                "9HB)WSL\n" +
                "L1R)5SB\n" +
                "G9Y)1BT\n" +
                "J26)91R\n" +
                "WR2)H46\n" +
                "2RC)K16\n" +
                "QJN)VVV\n" +
                "4QD)G3Y\n" +
                "XBV)35M\n" +
                "QPK)RR2\n" +
                "S72)T84\n" +
                "Q2B)5PT\n" +
                "39J)MBH\n" +
                "VFM)QSY\n" +
                "G2Z)KDD\n" +
                "Y94)ZS2\n" +
                "MTV)NPB\n" +
                "R49)B31\n" +
                "RVX)TZR\n" +
                "MD2)V1V\n" +
                "9TD)MDB\n" +
                "WYV)YFB\n" +
                "FRZ)C2K\n" +
                "DPB)CTJ\n" +
                "5JB)M8Z\n" +
                "4DY)WQ8\n" +
                "KGH)WZS\n" +
                "35W)3RK\n" +
                "1SN)PSP\n" +
                "VGN)5WS\n" +
                "BR8)8JH\n" +
                "N2Z)ZXR\n" +
                "TJY)29N\n" +
                "8JN)S81\n" +
                "4FV)3Y3\n" +
                "QFZ)F7Y\n" +
                "H7D)FFZ\n" +
                "TVY)BMM\n" +
                "8VK)395\n" +
                "N3H)X1J\n" +
                "6RS)HQH\n" +
                "42J)FCX\n" +
                "6TF)R3Y\n" +
                "4K2)7R8\n" +
                "BGJ)2JZ\n" +
                "7F8)G92\n" +
                "BMS)6CM\n" +
                "HTZ)ZM5\n" +
                "HQH)8P7\n" +
                "MXC)7LR\n" +
                "M3K)YKV\n" +
                "54P)TJD\n" +
                "FS4)28V\n" +
                "7PW)WNF\n" +
                "HMR)SGC\n" +
                "V5V)HBY\n" +
                "RM5)Z12\n" +
                "KZP)KCV\n" +
                "4P4)VWV\n" +
                "WZR)XYS\n" +
                "RNC)9Z8\n" +
                "QR4)JQ8\n" +
                "WSL)7S7\n" +
                "S81)DHH\n" +
                "NGC)7SR\n" +
                "6L9)8MB\n" +
                "DNH)44J\n" +
                "PVR)124\n" +
                "XZG)4X5\n" +
                "M6F)CB8\n" +
                "QJB)CZ7\n" +
                "DQW)XBV\n" +
                "PKH)RX7\n" +
                "GFS)7J9\n" +
                "W7N)DVH\n" +
                "96G)DQC\n" +
                "BWG)W6T\n" +
                "2BG)129\n" +
                "HHP)SJW\n" +
                "FGB)SBR\n" +
                "X6W)XHZ\n" +
                "5SB)MZ6\n" +
                "L5G)65M\n" +
                "WC5)1MT\n" +
                "3T6)CTB\n" +
                "YJF)JGZ\n" +
                "124)LB2\n" +
                "JDP)592\n" +
                "WV2)4D6\n" +
                "T7N)Y94\n" +
                "1SJ)ZTQ\n" +
                "CKS)KHG\n" +
                "1SR)4L5\n" +
                "6N5)3BR\n" +
                "22T)BQD\n" +
                "NBG)CSL\n" +
                "1ZG)DYK\n" +
                "P8G)DRK\n" +
                "LKD)RPY\n" +
                "7S3)9PB\n" +
                "ZTM)RNC\n" +
                "3QH)Y21\n" +
                "VXH)LDQ\n" +
                "NVL)QD7\n" +
                "TDC)TM4\n" +
                "W5C)YHB\n" +
                "19S)MS9\n" +
                "MNM)SJ3\n" +
                "8MT)XY8\n" +
                "6J1)GWC\n" +
                "T5C)KBQ\n" +
                "DC1)MVM\n" +
                "QXD)N8B\n" +
                "LKT)F5D\n" +
                "HM1)TNY\n" +
                "DQC)S9W\n" +
                "RTL)QGK\n" +
                "J1T)FPT\n" +
                "CZ7)2N2\n" +
                "674)FC4\n" +
                "FMR)NLW\n" +
                "TKG)1JN\n" +
                "1P3)GLP\n" +
                "HK3)VTZ\n" +
                "RHW)PG9\n" +
                "LJQ)7B2\n" +
                "5ZB)7ZM\n" +
                "LFP)PQW\n" +
                "TY8)YS7\n" +
                "4BZ)QLX\n" +
                "9BX)TNS\n" +
                "S84)3PN\n" +
                "GGC)S4T\n" +
                "L5G)WX6\n" +
                "25S)JZJ\n" +
                "WK9)L5G\n" +
                "LBS)9V5\n" +
                "K7V)8MT\n" +
                "7Q6)G8X\n" +
                "4GN)HXM\n" +
                "VH3)XK8\n" +
                "N8B)882\n" +
                "83M)YG4\n" +
                "P51)YR7\n" +
                "CS3)YY7\n" +
                "SVZ)N1N\n" +
                "X5V)G9F\n" +
                "G7M)GRX\n" +
                "39P)16T\n" +
                "YBM)JDC\n" +
                "WDC)8K5\n" +
                "HLN)W9F\n" +
                "QVP)XR9\n" +
                "442)VSF\n" +
                "YJR)LZ3\n" +
                "86L)6TF\n" +
                "P2Z)LDL\n" +
                "PQW)PPG\n" +
                "CB8)1JB\n" +
                "W9F)CHH\n" +
                "VSK)RG1\n" +
                "SXM)QCR\n" +
                "969)WYR\n" +
                "6VG)F69\n" +
                "MLY)3VC\n" +
                "RDL)ZRH\n" +
                "X1Z)TWJ\n" +
                "1BT)RXF\n" +
                "4FX)T2D\n" +
                "L2J)LB5\n" +
                "VHJ)MNM\n" +
                "Y3N)3BG\n" +
                "GD8)4KR\n" +
                "8TJ)C79\n" +
                "CFJ)QVM\n" +
                "4YM)SXM\n" +
                "71W)2S1\n" +
                "16T)NR6\n" +
                "D5N)PC7\n" +
                "S47)2RW\n" +
                "2Q3)QQ3\n" +
                "6FN)9Y1\n" +
                "PZG)6B3\n" +
                "XD8)2D8\n" +
                "C39)TJN\n" +
                "WYR)HWJ\n" +
                "HG1)RLC\n" +
                "CQM)7G7\n" +
                "WF2)NPD\n" +
                "VWV)643\n" +
                "JLZ)B2B\n" +
                "Z5H)BFV\n" +
                "LX9)1T4\n" +
                "CBG)3ZL\n" +
                "9HQ)8JN\n" +
                "F18)Q7J\n" +
                "F4M)W86\n" +
                "Q7J)YHM\n" +
                "6BQ)4FM\n" +
                "8CV)ZN4\n" +
                "YPR)NW2\n" +
                "VFT)FDW\n" +
                "DFP)JT7\n" +
                "Y6J)ZK7\n" +
                "C2P)CBY\n" +
                "3Y3)TVR\n" +
                "97M)JLZ\n" +
                "RG1)YB3\n" +
                "1J2)DLX\n" +
                "V7H)D6J\n" +
                "6B3)8BK\n" +
                "NW2)F94\n" +
                "PLY)D38\n" +
                "J3R)WYP\n" +
                "4GM)9TZ\n" +
                "D34)44G\n" +
                "QXC)B23\n" +
                "L68)797\n" +
                "HH4)1XF\n" +
                "N2S)ZJR\n" +
                "JJF)CXL\n" +
                "L24)Z5P\n" +
                "YHM)JB4\n" +
                "5FX)DW4\n" +
                "5WR)KYM\n" +
                "1SS)QCJ\n" +
                "9V5)RWZ\n" +
                "ZXY)FD8\n" +
                "VHL)6JG\n" +
                "RTN)Y5Q\n" +
                "JGP)H5F\n" +
                "2T5)7NT\n" +
                "LLY)TWZ\n" +
                "SYL)HSJ\n" +
                "BK8)3NR\n" +
                "VG8)D8J\n" +
                "Z18)T5X\n" +
                "G7S)N6M\n" +
                "9JZ)BR8\n" +
                "BM4)8HF\n" +
                "DXP)7D7\n" +
                "PG9)3SQ\n" +
                "P9Y)J7T\n" +
                "47G)TGL\n" +
                "9BX)JGP\n" +
                "HXM)7TN\n" +
                "JQ4)LQ5\n" +
                "6MS)VP7\n" +
                "2BL)3WC\n" +
                "T1W)WW8\n" +
                "YDQ)NQW\n" +
                "1FL)Z3H\n" +
                "JCX)WHG\n" +
                "6ZK)L3H\n" +
                "DZS)TXB\n" +
                "Z4P)6BQ\n" +
                "Y5T)9V7\n" +
                "5WQ)HN5\n" +
                "DGK)C1Y\n" +
                "FSN)ZLF\n" +
                "72P)DNH\n" +
                "19S)K14\n" +
                "QPK)FRL\n" +
                "6QW)VGS\n" +
                "5V9)2C7\n" +
                "BYK)RQV\n" +
                "1JN)XWF\n" +
                "34W)6RP\n" +
                "QFS)SF7\n" +
                "Y61)CKW\n" +
                "R33)NNT\n" +
                "MS9)4Q1\n" +
                "M74)FVN\n" +
                "RX1)S4G\n" +
                "116)4BB\n" +
                "YQQ)MC2\n" +
                "ZN4)1BY\n" +
                "RLS)BBC\n" +
                "B2J)11H\n" +
                "P6P)F6H\n" +
                "KD7)R9K\n" +
                "FCV)ZVJ\n" +
                "ZTX)HZ2\n" +
                "VMM)SGD\n" +
                "5H6)Q2B\n" +
                "L1R)9Z9\n" +
                "H83)FCV\n" +
                "F91)B45\n" +
                "L4S)PP4\n" +
                "2VB)R69\n" +
                "YB6)4GN\n" +
                "5ST)1DM\n" +
                "3L3)J2L\n" +
                "ZRX)2RC\n" +
                "5GL)S3X\n" +
                "7LR)N2Z\n" +
                "3RL)P2D\n" +
                "ZHJ)TJY\n" +
                "DCJ)2XS\n" +
                "PHY)96G\n" +
                "MDB)QFS\n" +
                "SH8)LZ7\n" +
                "VSF)CCC\n" +
                "XMT)35D\n" +
                "YKR)GB4\n" +
                "X41)Y3P\n" +
                "MN8)2Q3\n" +
                "LNG)NHD\n" +
                "K8N)DTH\n" +
                "H2X)J1T\n" +
                "5LM)Y1B\n" +
                "JT7)6J1\n" +
                "VR4)P53\n" +
                "813)JW7\n" +
                "CNL)QXD\n" +
                "PRY)MG1\n" +
                "S3D)R68\n" +
                "JGZ)PXX\n" +
                "1NW)S72\n" +
                "FYH)3RL\n" +
                "48R)CWM\n" +
                "2RW)6ZW\n" +
                "6DS)MNG\n" +
                "FD8)238\n" +
                "FZN)HYR\n" +
                "NHL)THR\n" +
                "Z98)65Z\n" +
                "TRM)QLM\n" +
                "K38)W3R\n" +
                "4D6)WZ1\n" +
                "BWD)2GQ\n" +
                "FRL)DKZ\n" +
                "WZ6)HC9\n" +
                "BBN)7PN\n" +
                "DJJ)DRJ\n" +
                "3YQ)17B\n" +
                "KCV)YTH";

        System.out.println("Solution for day 6 part 1 is: " + day6.orbitsTotal(input));
    }
}
